baseurl = "/"
languageCode = "en-us"
title = "Homepage"
theme = "prologue"

[params]
  name = "Wanderland Travelers"
  description = "Adventure. Travel. Open Spaces"
  copyright = "Untitled."

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://youtube.com/wanderlandtravelers"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://facebook.com/wanderlandtravelers"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://instagram.com/wanderlandtravelers"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/wanderlandistas"